/**
 * Shared type barrel.
 *
 * Domain-specific type modules (`chat.types.ts`, `agent.types.ts`,
 * `incident.types.ts`, ...) are added by the phases that introduce them.
 * `database.types.ts` is generated by `npm run db:types` in Phase 4 and must
 * never be hand-edited.
 */

export type { UserRole, Surface, ErrorCode } from '@/config/constants';

/**
 * Dependency health, as reported by `GET /api/v1/health` (section 22.3).
 *
 * `not_configured` distinguishes "this infrastructure has not been set up yet"
 * from "it is set up and broken". A fresh clone has neither Postgres nor Redis,
 * and that is a supported state — reporting it as `down` would be misleading.
 */
export type DependencyStatus = 'up' | 'down' | 'degraded' | 'not_configured';

export interface DependencyHealth {
  readonly status: DependencyStatus;
  readonly latencyMs: number | null;
  readonly note?: string;
}

export interface HealthReport {
  readonly status: DependencyStatus;
  readonly timestamp: string;
  readonly version: string;
  readonly dependencies: Readonly<Record<string, DependencyHealth>>;
}

/** Standard API response envelope (section 8.2). */
export interface ApiMeta {
  readonly requestId: string;
  readonly timestamp: string;
  readonly durationMs?: number;
}

export interface ApiSuccess<T> {
  readonly success: true;
  readonly data: T;
  readonly meta: ApiMeta;
}

export interface ApiErrorDetail {
  readonly path: string;
  readonly message: string;
}

export interface ApiFailure {
  readonly success: false;
  readonly error: {
    readonly code: string;
    readonly message: string;
    readonly details?: readonly ApiErrorDetail[];
  };
  readonly meta: ApiMeta;
}

export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;
